name: Build

on:
  push:
    branches:
      - release/v*
    # Run the workflow when pushing to the main branch

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_INSTALL_DIR: "./.dotnet"
  NUGGETDIRECTORY: ${{github.workspace}}/nuget
  PROJECT_PATH: EntityFrameworkToolKit
  NUGGET_SOURCE: https://nuget.pkg.github.com/wearemiew/index.json

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using 
      
    - name: Extract Version
      run: |
          # Get the branch name from the GitHub context
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          # Extract the version part after 'release/'
          VERSION="${BRANCH_NAME#release/}"
          # Remove the leading 'v' if it exists
          VERSION="${VERSION#v}"
          echo "Branch Name: $BRANCH_NAME"
          echo "Extracted Version: $VERSION"
          # Set the version as an output
          echo "version=$VERSION" >> $GITHUB_ENV
          
    - name: Use the Version
      run: |
          echo "The version is: ${{env.VERSION}}
          
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
        # Install the .NET SDK indicated in the global.json file
    - name: Download .net
      uses: actions/setup-dotnet@v3

    - name: Pack nugget package
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release -p:PackageVersion=${{env.VERSION}} --output ${{env.NUGGETDIRECTORY}}

    - name: Publish NuGet package
      run: dotnet nuget push ${{env.NUGGETDIRECTORY}}/*.nupkg -k ${GITHUB_TOKEN} -s ${{env.NUGGET_SOURCE}}  --no-symbols 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create a Release
    #   uses: elgohr/Github-Release-Action@v4
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #       title: v${version}
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branches: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'master',
            'next',
            'next-major',
            {
              name: 'beta',
              prerelease: true
            },
            {
              name: 'alpha',
              prerelease: true
            }
          ]
