name: Build

on:
  release:
    types: [created]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_INSTALL_DIR: "./.dotnet"
  NUGGETDIRECTORY: ${{github.workspace}}/nuget
  PROJECT_PATH: EntityFrameworkToolKit
  NUGGET_SOURCE: https://nuget.pkg.github.com/wearemiew/index.json

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using 
      
    - name: Extract Version from Release
      id: extract_version
      run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
    - name: Use the Version
      run: |
          echo "The version is: ${{env.version}}"
          
    - name: Download .NET SDK
      uses: actions/setup-dotnet@v3

    - name: Pack NuGet package
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release -p:PackageVersion=${{ env.VERSION }} --output ${{ env.NUGGETDIRECTORY }}

    - name: Publish NuGet package
      run: dotnet nuget push ${{ env.NUGGETDIRECTORY }}/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s ${{ env.NUGGET_SOURCE }} --no-symbols
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send notification to Google Chat
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
            "cards": [
                {
                    "header": {
                        "title": "New Release Created",
                        "subtitle": "GitHub Release Notification",
                        "imageUrl": "https://avatars.githubusercontent.com/u/9919?s=200&v=4",
                        "imageStyle": "IMAGE"
                    },
                    "sections": [
                        {
                            "widgets": [
                                {
                                    "textParagraph": {
                                        "text": "🎉 *New Release:* ${{ github.event.release.name }}\n\n 🔖 *Tag:* ${{ github.event.release.tag_name }}\n🔗 *Release URL:* ${{ github.event.release.html_url }}\n\n📜 *Release Notes:*\n${{ github.event.release.body }}\n\n Created by: ${{ github.actor }}"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }' \
        'https://chat.googleapis.com/v1/spaces/AAAAp1BXZnQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=JWQ-U-3AA0K7ghbkhkTPzdIHpglLyjKBHrL8UclV0lM'
    
